# for mySQL
<%
socket = ["/tmp/mysqld.sock",
          "/tmp/mysql.sock",
          "/var/run/mysqld/mysqld.sock",
          "/var/lib/mysql/mysql.sock"].detect{|socket| File.exist?(socket)}
%>

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mmm_rails_development
  pool: 5
  username: root
  password: 
  socket: <%= socket %>

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mmm_rails_test
  pool: 5
  username: root
  password: 
  socket: <%= socket %>

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mmm_rails_production
  pool: 5
  username: root
  password: 
  socket: <%= socket %>

